---
name: Cloudflare Logs

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

env:
  PROJECT_NAME: website

concurrency:
  group: cloudflare-logs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cloudflare-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CF Pages
        id: cf-pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CF_LOG_TOKEN  }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          project: ${{ env.PROJECT_NAME }}
      - name: Post Cloudflare Pages Logs
        run: |
          # Get deployment id from Get Project call (https://developers.cloudflare.com/api/operations/pages-project-get-project)
          deployment_id=$(curl -sL https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/pages/projects/chatterino-website -H "Authorization: Bearer ${{ secrets.CF_LOG_TOKEN }}" | jq -r .result.latest_deployment.id)
          # Get deployment logs by deployment id (https://developers.cloudflare.com/api/operations/pages-deployment-get-deployment-logs)
          deployment_logs="$(curl -sL https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/pages/projects/chatterino-website/deployments/$deployment_id/history/logs -H "Authorization: Bearer ${{ secrets.CF_LOG_TOKEN }}" | jq -r ".result.data | map(.line)")"
          echo "$deployment_logs"
